### ISSUE TITLE
Support Parameterized Runner

### ISSUE THREAD

**Issue by zlippard** [linkedin/dex-test-parser#17]
Was looking to get support for the `Parameterized` runners.  Currently this is an issue in Flank (https://github.com/TestArmada/flank/issues/61) but it sounds like the support for this type of runner needs to be enabled here first.

**Comment by zlippard** [comment]
I would be willing to help contribute for this request, but wasn't sure where to start for supporting this runner type.

**Comment by drewhannay** [comment]
I did some quick testing and I don't see any issues with dex-test-parser for this. I can put up my sample code later today, but it seems like we find the test methods as expected.

On another note though, I'd strongly recommend against using the `Parameterized` runner on Android, because it makes it impossible to run each instance of the test in its own isolated instance of the application. This is because the splitting / sharding / parameterization of the test is happening inside the app by the `Parameterized` runner class, rather than outside the app (which is what something like dex-test-parser allows).

**Comment by drewhannay** [comment]
Here's the sample I used:
https://gist.github.com/drewhannay/4c838f1aa577050f85ed6ab268098099

When I run this from Android Studio, it invokes:
`adb shell am instrument -w -r   -e debug false -e class 'com.linkedin.parser.test.junit4.java.ParameterizedTest#sampleTest' com.linkedin.parser.test.test/android.support.test.runner.AndroidJUnitRunner`

When I run dex-test-parser, it outputs:
`com.linkedin.parser.test.junit4.java.ParameterizedTest#sampleTest`
which seems correct to me.

**Comment by zlippard** [comment]
Thanks so much for the confirmation @drewhannay!  Was this fixed perhaps with the `2.0.0` release?  It was the impression of the Flank devs that `Parameterized` was not recently supported in this library.   So maybe the new release is what is supporting this runner?

Will also take your suggestion in to account regarding the use of this runner in general.

**Comment by drewhannay** [comment]
I don't know of any reason this wouldn't have worked in older versions of dex-test-parser, although I haven't tested that.
