### ISSUE TITLE
parser.jar not working from command-line

### ISSUE THREAD

**Issue by vrunoa** [linkedin/dex-test-parser#18]
I rebuild the project from source and when trying to use `java -jar` the command-line fails. 

Steps to reproduce:
```bash
./gradlew clean build
java -jar parser/build/distributions/parser-2.0.1-SNAPSHOT/lib/parser-2.0.1-SNAPSHOT.jar test-app/build/outputs/apk/test-app-debug-androidTest.apk ./
```

Error
```
no main manifest attribute, in parser/build/distributions/parser-2.0.1-SNAPSHOT/lib/parser-2.0.1-SNAPSHOT.jar
```

Environment
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
```

**Comment by drewhannay** [comment]
I think the problem here is you're trying to run with the wrong jar file. You should be using:

```
java -jar parser/build/libs/parser-2.0.1-SNAPSHOT-all.jar test-app/build/outputs/apk/test-app-debug-androidTest.apk ./
```

Note the `-all` in the filename. The one you're using is the jar that doesn't include all dependencies and is used when consuming the project from Gradle rather than CLI. That jar probably doesn't need the main class set, but we DO set it already in the `-all` jar (see [this line](https://github.com/linkedin/dex-test-parser/blob/master/parser/build.gradle#L8) )

**Comment by vrunoa** [comment]
@drewhannay yeap you were right. Closing this issue. Perhaps we can make a note on the README.md for people to make sure to use`-all` libs when running it from command-line.
