### ISSUE TITLE
Parsing kotlin interfaces is wrong

### ISSUE THREAD

**Issue by thalescm** [linkedin/dex-test-parser#3]
When using this library on a test apk which contains [kotlin interfaces](https://kotlinlang.org/docs/reference/interfaces.html) with methods annotated with `@Test`, this library will put the fully qualified name for this interface, when it shouldn't (it's not a runnable test unless you have a real class implementing it)

**Comment by drewhannay** [comment]
Interesting...does this work properly when run with AndroidJUnitRunner alone? I was not aware that it's valid to annotate an interface method with `@Test`

**Comment by thalescm** [comment]
@drewhannay It works properly with AndroidJUnitRunner.
Kotlin interfaces `can contain declarations of abstract methods, as well as method implementations` (as said in the documentation sent above). So it's possible to have an interface containing the implementation of a common method annotated with `@Test` (which is my case).

AndroidJUnitRunner probably make checks to see if it is a class to define the method as runnable.
Also, it is important to check if this library will be able to match the tests to all classes implementing the interface in question, otherwise there would be tests missing on the final result (this behavior I did not test to see if happens)

**Comment by drewhannay** [comment]
I think I understand the issue here, but any chance you can throw up a sample project somewhere that I can test against to ensure this gets fixed properly?

**Comment by thalescm** [comment]
@drewhannay I'll try to find time to do that. Will let you know when that happens. And you can feel free to add the project's apk here (once created) in case you wanna unit test it to guarantee for future changes :D

**Comment by thalescm** [comment]
Hi @drewhannay.

Made the sample project [here](https://github.com/thalescm/DexParserKotlinInterfaceBugApp)

There's a README explaining the situation there as well. Also, there's a folder `apks` on it with the apks so you don't have to build the project to get them :)

**Comment by drewhannay** [comment]
@thalescm I spent some time working on this today and I think there are multiple things going on here. This is a fun one 😄   Also, your sample project was EXTREMELY helpful, so thanks for making it.

First, `@Test` on an interface method seems to me like it would never be a real test method, whether java or kotlin. I could reproduce the dex-test-parser bug with this Java interface as well:
```
public interface SampleTest {
    @Test
    void sampleTest();
}
```

This is an easy fix in dex-test-parser and I'll put up a PR today with the fix to exclude these interface methods.

------------------------------------------------------------

The other "unwanted" method in your sample project is more interesting:
`machado.thales.dexparserkotlininterfacebugapp.SurpriseButtonTest$DefaultImpls#testClickWillShowSurprise`

It looks like the bytecode Kotlin generates for the interface is equivalent to this java code:
```
public interface SampleTest {

    @Test
    void sampleTest();

    public static final class DefaultImpls {
        @Test
        public static void sampleTest() {
            // default impl here
        }
    }
}
```

This seems like it SHOULD be valid...in fact, if I run this exact same test as a JVM unit test, it works perfectly.

As a further experiment, I tried modifying my test case to use an outer class instead of an interface:
```
public class OuterClass {
    public static final class InnerClass {
        @Test
        public static void innerTest() {
            // test impl here
        }
    }
}
```

This also works perfectly in JVM unit tests. With `AndroidJUnitRunner`, however, the results seem to vary. If I run the test by running all the tests in the package, this one runs as expected (but the `interface` version still does not run). But if I try running the "outer class" individual test via Android Studio, it tells me "Empty test suite". This is because it tried to run this adb command:
`adb shell am instrument -w -r   -e debug false -e class machado.thales.dexparserkotlininterfacebugapp.OuterClass.InnerClass#innerTest machado.thales.dexparserkotlininterfacebugapp.test/android.support.test.runner.AndroidJUnitRunner`

Notice that it's using `OuterClass.InnerClass` rather than `OuterClass$InnerClass`. This seems like a definite bug in Android Studio, which I will report.

If I try to manually run the corrected adb command from the command line myself, it _still_ fails, but for a different reason this time. AndroidJUnitRunner was trying to run `machado.thales.dexparserkotlininterfacebugapp.OuterClass#innerTest` (missing `InnerClass`). 

Turns out the reason for this is that you need TWO forms of escaping in your adb command. It should be:
`adb shell 'am instrument -w -r   -e debug false -e class machado.thales.dexparserkotlininterfacebugapp.OuterClass\$InnerClass#innerTest machado.thales.dexparserkotlininterfacebugapp.test/android.support.test.runner.AndroidJUnitRunner'`
Notice the `'` around `am ...` and the `\$`.

If I run the test from the command line with the proper escaping, it runs as expected (same as the JVM version).

I then went back and ran the `interface` inner class test manually from the command line with the proper escaping and that _also_ worked as expected. It seems like something in the AndroidJUnitRunner code that searches for tests in a package is ignoring interfaces and not looking inside them for inner classes (which seems incorrect to me).

------------------------------------------------------------

Given that super long explanation, I'm not entirely sure what to do next for this second issue. It seems like I have a number of bugs to report to the Android Studio team (which I will do). I think there's also a separate bug to report to the Android Testing Support Library team regarding "run all in package" not looking inside interfaces for inner classes.

I do think it's fairly clear that dex-test-parser shouldn't be _ignoring_ tests in inner classes, although that doesn't solve your Kotlin problem. One solution for you might be for you to filter the list of found tests and strip out anything with `$DefaultImpls` in the name. I don't think it would be right for dex-test-parser to do this though.

What I'm not sure about is this:
Should dex-test-parser escape the `$` in its output? I'm leaning towards "no" and saying this is the responsibility of the user of dex-test-parser, since they would also need to add the `'` escaping in their adb command already. I'm curious to hear any alternate opinions on this though.

**Comment by yogurtearl** [comment]
I agree you should NOT escape the `$`. The need for escaping is a implementation detail of the shell, not part of the class name.

**Comment by thalescm** [comment]
@drewhannay Awesome man!
Thanks so much for dedicating time to it, and for that detailed explanation about the real problem underneath!

I agree with you and @yogurtearl that it's not this libs responsibility to scape the `$` symbol on the result.

As of my case, in this meanwhile, your suggestion makes sense. Thanks!

**Comment by drewhannay** [comment]
Created two Android bug tracker issues:
https://issuetracker.google.com/issues/63752700
https://issuetracker.google.com/issues/63753968
