### ISSUE TITLE
Unable to build the project

### ISSUE THREAD

**Issue by doodla** [linkedin/dex-test-parser#47]
The project dependencies are extremely out of date and there are no instructions on how to get it to run locally.

I tried Android Studio, but it just wouldn't build.

Android Studio -> Import Project -> Gradle Project

**Comment by jasmsu** [comment]
Hey there! This isn't an Android project, so I wouldn't suggest using Android Studio as an IDE to build this. Intellij (or some other Java IDE) may be a better choice, and may solve some of the issues your were hitting. If you're still having trouble building, please pass along some more details on what went wrong with the build. Thanks!

**Comment by drewhannay** [comment]
With #52, the dependencies should mostly all be updated and be buildable in a modern Android Studio or IntelliJ. We'll likely continue to make more improvements to the build setup as we work towards publishing on Maven Central instead of JCenter, but I think the current state is sufficient to close this ticket. Sorry for the long delay 😢
