### ISSUE TITLE
Get annotation values?

### ISSUE THREAD

**Issue by zsperske** [linkedin/dex-test-parser#8]
Thanks for building this! We're planning on using this as part of our test process and I was wondering, we can fetch annotation names but how about their values? "@ Foo("Bar")". I've just pulled down the code and was planning on investigating myself but just wanted to check in and see if there was anything that stopped you?

**Comment by drewhannay** [comment]
What would be the use case? I'm a bit worried that it's a slippery slope towards this project turning into a full blown decompiler for test apks, which wasn't really the intention or goal of the project :)

**Comment by zsperske** [comment]
Haha that's fair, though I do think this could be useful. We use toggles with various states (production, preview, internal) to expose/hide features in different environments. I'm working on building annotations for our tests like @ ActivatedBy("Toggle1") which would only run that test if that toggle was active in the environment the test was running on. Similarly @ DeprecatedBy("toggle1") would not run the test if that toggle was on.

**Comment by zsperske** [comment]
Any thoughts on this guy? One option on our end is to create annotations for each toggle but... we'd prefer not to do that.

**Comment by drewhannay** [comment]
I think an alternate way of doing what you're describing would be to use the JUnit `assumeTrue()` method and just skip the tests that don't apply at runtime instead of trying to to filter them out ahead of time.

For example, in your rule that processes the `@ActivatedBy` annotation, you could have something like `assumeTrue(currentToggle.equals(annotation.value())`. Then the test would show up as "Skipped" (rather than passed or failed) in your junit report. Unless you have thousands of tests that would be skipped, this shouldn't have too much impact on your test execution time.

**Comment by zsperske** [comment]
Ah that's an interesting idea, thanks for your responses! Will close this.
